* City Pop
:PROPERTIES:
:CUSTOM_ID: city-pop
:END:
[[https://en.wikipedia.org/wiki/City_pop][City Pop]] is a Japanese music
genre from the 1980s. A time when japan had an economic and
technological boom.

City Pop is kind of a mix between soft rock, funk, disco, R&B, and pop.

*** Playlists
:PROPERTIES:
:CUSTOM_ID: playlists
:END:
- [[https://www.youtube.com/watch?v=tnwDVc3R_CI&list=PL0IrpCjpbz8BnI0YwBLi3d3P74XuN6CD9][Tatsuro
  Yamashita]]
- [[https://www.youtube.com/watch?v=dOSESpbQ19Y][Come Along - Tatsuro
  Yamashita]] - radio host
  [[https://en.wikipedia.org/wiki/Kamasami_Kong][Kamasami Kong]]
- [[https://youtu.be/ZMr-VXF4xkY][Best of Tatsuro Yamashita]]
- [[https://youtu.be/eGslweDOihs][City Pop Playlist]]
- [[https://youtu.be/ZBYwUaoJquM][Mellow Days Playlist]]

#+begin_quote
sidenote: Tatsuro Yamashita makes me want to buy a telecaster
#+end_quote

*** Plastic Love
:PROPERTIES:
:CUSTOM_ID: plastic-love
:END:
[[https://en.wikipedia.org/wiki/Plastic_Love][Plastic Love]] is an
excellent song by city pop legend Mariya Takeuchi. The song wasn't that
popular when it originally came out, but in modern day, Plastic Love has
become insanely popular thanks to the power of the internet.

Plastic love is a narrative that touches on how we lean on
consumerism(buying electronics) to fill in the dark/empty lives we have.

From a musical perspective, I find it interesting that the chorus/hook
of the song doesn't show up until the song is about 80% done.

- [[https://youtu.be/9Gj47G2e1Jc][Plastic Love - Mariya Takeuchi]]
- [[https://youtu.be/PlPTXR7e6As][Plastic Love Documentary]] ❤️❤️❤️
- [[https://youtu.be/JGTZCrqCjCM][Plastic Love -- sick dance moves]]
