* Reps
:PROPERTIES:
:CUSTOM_ID: reps
:END:
Reps, as in repetition.

*** The Practice
:PROPERTIES:
:CUSTOM_ID: the-practice
:END:

#+begin_quote
"Do it. Simply do it. Merely do it. Do it without commentary. Do it
without drama. If it doesn't work today, do it again tomorrow."”
#+end_quote

#+begin_quote
-- Seth Godin
#+end_quote

https://seths.blog/thepractice/

*** Don't wait to be perfect, do your reps
:PROPERTIES:
:CUSTOM_ID: dont-wait-to-be-perfect-do-your-reps
:END:
[[https://seths.blog/2020/06/the-simple-cure-for-writers-block/]["Have
writers block? ...Show me your bad writing"]]

*** The Ceramics Anecdote
:PROPERTIES:
:CUSTOM_ID: the-ceramics-anecdote
:END:

#+begin_quote
/“The ceramics teacher announced on opening day that he was dividing the
class into two groups. All those on the left side of the studio, he
said, would be graded solely on the quantity of work they produced, all
those on the right solely on its quality./

/His procedure was simple: on the final day of class he would bring in
his bathroom scales and weigh the work of the “quantity” group: fifty
pound of pots rated an “A”, forty pounds a “B”, and so on. Those being
graded on “quality”, however, needed to produce only one pot -- albeit a
perfect one -- to get an “A”./

/Well, came grading time and a curious fact emerged: the works of
highest quality were all produced by the group being graded for
quantity. It seems that while the “quantity” group was busily churning
out piles of work -- and learning from their mistakes -- the “quality”
group had sat theorizing about perfection, and in the end had little
more to show for their efforts than grandiose theories and a pile of
dead clay.”/ --
[[https://www.goodreads.com/book/show/187633.Art_and_Fear][Art & Fear]]
#+end_quote

**** True Story
:PROPERTIES:
:CUSTOM_ID: true-story
:END:
[[https://jamesclear.com/repetitions][James Clear]] reached out to the
authors of Art & Fear. However, the medium was originally photography.
