* Spaced Repetition
:PROPERTIES:
:CUSTOM_ID: spaced-repetition
:END:
A system to help facilitate rote memorization.

One of the most popular
[[https://en.wikipedia.org/wiki/Spaced_repetition][Spaced Repetition
Systems (SRS)]] is [[https://apps.ankiweb.net/][Anki]].

Anki is a great way to transfer the content that you are studying into
long term memory. I should point out that this should only be necessary
in a few situations. It's much more efficient to be able to reference
something rather than memorizing it. However, you may want to commit
something fully to memory (e.g. learning
[[https://en.wikipedia.org/wiki/Kanji#:~:text=Kanji%20(%E6%BC%A2%E5%AD%97%2C%20pronounced%20%5Bka%C9%B2d%CA%91i,literally%20means%20%22Han%20characters%22.)][Kanji]]

The basic concept is that if you're familiar with something, you will
see that card less frequently. The things you aren't familiar will show
up more often. It's required of you to judge yourself honestly (i.e. you
will be in control of deciding how well you know something).

** Custom SRS
:PROPERTIES:
:CUSTOM_ID: custom-srs
:END:
I built a custom SRS for learning
[[https://en.wikipedia.org/wiki/Hiragana][hiragana]] and
[[https://en.wikipedia.org/wiki/Katakana][katakana]]

[[https://dfirebaugh.github.io/kana-board/][kana board demo]]

This is basically digital flash cards.

** Custom vs Anki
:PROPERTIES:
:CUSTOM_ID: custom-vs-anki
:END:
I would Anki is great if you're really trying to commit something to
long term memory. It has systems that will space cards that you're
comfortable with over several days and sometimes weeks.

A custom solution would be better if you're just trying to capture the
basic concepts of something that you can then reference later. It might
also be good for learning something that isn't extremely dense. With the
custom solution, I was able to learn (read not write) hiragana fairly
well in less than a week.
